export const Roles = Object.freeze({
    CAN_VIEW_BRANCH_HOLIDAYS: 'CAN_VIEW_BRANCH_HOLIDAYS',
    CAN_APPROVE_BRANCH_HOLIDAYS: 'CAN_APPROVE_BRANCH_HOLIDAYS',
    CAN_CREATE_ROSTER: 'CAN_CREATE_ROSTER',
    CAN_VIEW_BRANCH_USERS: 'CAN_VIEW_BRANCH_USERS',
    CAN_CREATE_ANNOUNCEMENT: 'CAN_CREATE_ANNOUNCEMENT',
})